---
    version: '2'
    services:
      zookeeper:
        image: zookeeper:3.6.2
        hostname: zookeeper
        container_name: zookeeper

      broker:
        image: bsucaciu/kafka:2.6.0
        hostname: broker
        container_name: broker
        depends_on:
          - zookeeper
        ports:
          - "9092:9092"   
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
          KAFKA_LISTENERS: PLAINTEXT://broker:9092
    